name: Build static site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          npm run build
          git commit -a -m "Build static site"
          git push origin master
